<a href="https://colab.research.google.com/github/ashishrautela123/American-Express-Data-Analysis/blob/main/Ameican_Express_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning via ANN

## Importing libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

## Importing dataset

In [3]:
dataset = pd.read_csv('American.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


## Encoding categorical data

### Gender column : Label Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])

In [6]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


### Geography column : One hot Encoding

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


## Splitting dataset into Training & Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## ANN

### Initialization

In [11]:
ann = tf.keras.models.Sequential()

### Adding input layer and first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## ANN Training

### Compiling ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training on training dataset

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

Epoch 1/120
249/249 [==============================] - 1s 2ms/step - loss: 0.5943 - accuracy: 0.7184
Epoch 2/120
249/249 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7970
Epoch 3/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4552 - accuracy: 0.7969
Epoch 4/120
249/249 [==============================] - 1s 2ms/step - loss: 0.4450 - accuracy: 0.7981
Epoch 5/120
249/249 [==============================] - 1s 2ms/step - loss: 0.4391 - accuracy: 0.8008
Epoch 6/120
249/249 [==============================] - 1s 2ms/step - loss: 0.4351 - accuracy: 0.8039
Epoch 7/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4327 - accuracy: 0.8056
Epoch 8/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4312 - accuracy: 0.8073
Epoch 9/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4301 - accuracy: 0.8077
Epoch 10/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4288 - accura

# Predictions

### Single Prediction

In [17]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 [==============================] - 0s 475ms/step
[[False]]


### Predication on testset

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


### Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1505   68]
 [ 219  194]]


0.8554884189325277